Repository terraform-providers/terraform-provider-postgresql, pull requests merged in 2019-12, with the labels that each got.

#100 resource_postgresql_schema: Add database optional parameter
  postgresql/helpers.go
  postgresql/resource_postgresql_schema.go
  postgresql/resource_postgresql_schema_test.go
Labels: size/L

#103 Trust `expected_version` if provided
  postgresql/config.go
  postgresql/provider.go
Labels: size/XS

#108 postgresql_schema: Add drop_cascade option.
  CHANGELOG.md
  postgresql/resource_postgresql_schema.go
  postgresql/resource_postgresql_schema_test.go
  website/docs/r/postgresql_schema.html.markdown
Labels: documentation, size/S

#105 [add] set statement_timeout to role
  postgresql/helpers.go
  postgresql/resource_postgresql_role.go
  postgresql/resource_postgresql_role_test.go
Labels: size/M
