Repository terraform-providers/terraform-provider-postgresql, pull requests merged in 2019-05, with the labels that each got.

#75 Add missing quotes
  website/docs/r/postgresql_default_privileges.html.markdown
Labels: documentation, size/XS

#76 Add IF NOT EXISTS to CREATE EXTENSION
  postgresql/resource_postgresql_extension.go
Labels: size/XS

#78 Unifies the test acc setup and simplifies the travis script
  .travis.yml
  GNUmakefile
  README.md
  tests/env.sh
  tests/testacc_cleanup.sh
  tests/testacc_full.sh
  tests/testacc_setup.sh
Labels: enhancement, size/M
