Repository terraform-providers/terraform-provider-postgresql, pull requests merged in 2019-02, with the labels that each got.

#61 Travis: Build agains multiple Postgres version + fix bugs
  .travis.yml
  CHANGELOG.md
  postgresql/config.go
  postgresql/resource_postgresql_database.go
  postgresql/resource_postgresql_database_test.go
  postgresql/resource_postgresql_extension.go
  postgresql/resource_postgresql_extension_test.go
  postgresql/resource_postgresql_role.go
  tests/docker-compose.yml
  tests/env.sh
  tests/wait-postgres-docker.sh
Labels: bug, size/L

#58 config: Add a database_username parameter for users map.
  CHANGELOG.md
  postgresql/config.go
  postgresql/provider.go
  postgresql/resource_postgresql_database.go
  postgresql/resource_postgresql_role.go
  website/docs/index.html.markdown
Labels: documentation, enhancement, size/S

#59 Fix the way the owner is granted / revoked when managing a database.
  CHANGELOG.md
  postgresql/helpers.go
  postgresql/resource_postgresql_database.go
  postgresql/resource_postgresql_database_test.go
  postgresql/utils_test.go
Labels: bug, size/XL

#65 tests: Configure provider before running test
  postgresql/provider_test.go
Labels: bug, size/XS

#66 postgresql_role: Don't refresh password from Postgres if not superuser
  CHANGELOG.md
  postgresql/config.go
  postgresql/provider.go
  postgresql/resource_postgresql_role.go
  postgresql/resource_postgresql_role_test.go
Labels: bug, rds, size/L
