Repository terraform-providers/terraform-provider-postgresql, pull requests merged in 2019-03, with the labels that each got.

#68 Add documentation for `superuser` provider setting
  website/docs/index.html.markdown
Labels: documentation, size/XS

#53 New resources: postgresql_grant & postgresql_default_privileges
  CHANGELOG.md
  postgresql/config.go
  postgresql/helpers.go
  postgresql/provider.go
  postgresql/resource_postgresql_database.go
  postgresql/resource_postgresql_database_test.go
  postgresql/resource_postgresql_default_privileges.go
  postgresql/resource_postgresql_default_privileges_test.go
  postgresql/resource_postgresql_extension_test.go
  postgresql/resource_postgresql_grant.go
  postgresql/resource_postgresql_grant_test.go
  postgresql/resource_postgresql_role.go
  postgresql/resource_postgresql_role_test.go
  postgresql/resource_postgresql_schema.go
  postgresql/utils_test.go
  vendor/github.com/hashicorp/terraform/helper/structure/expand_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/flatten_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/normalize_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/suppress_json_diff.go
  vendor/github.com/hashicorp/terraform/helper/validation/validation.go
  website/docs/r/postgresql_default_privileges.html.markdown
  website/docs/r/postgresql_grant.html.markdown
  website/postgresql.erb
Labels: dependencies, documentation, enhancement, size/XXL

#69 Use literal quotes with VALID UNTIL
  postgresql/resource_postgresql_role.go
  postgresql/resource_postgresql_role_test.go
Labels: size/XS
