Repository terraform-providers/terraform-provider-postgresql, pull requests merged in 2020-04, with the labels that each got.

#126 Provider Configuration: Support SSL Client Certificates
  postgresql/config.go
  postgresql/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/M

#128 Fix max_connections validations.
  postgresql/provider.go
Labels: size/XS

#129 put resource type in quotes to align with syntax.
  website/docs/r/postgresql_grant.html.markdown
Labels: documentation, size/XS

#123 Implement grants on database
  postgresql/helpers.go
  postgresql/resource_postgresql_default_privileges.go
  postgresql/resource_postgresql_grant.go
  postgresql/resource_postgresql_grant_test.go
  postgresql/utils_test.go
Labels: size/XL
