Repository terraform-providers/terraform-provider-postgresql, pull requests merged in 2020-07, with the labels that each got.

#134 [resource_postgresql_default_privileges] add support for types default privileges
  postgresql/helpers.go
  postgresql/resource_postgresql_default_privileges.go
  postgresql/resource_postgresql_grant.go
  website/docs/r/postgresql_default_privileges.html.markdown
Labels: documentation, size/XS

#146 all resources: Grant object owners to connected user when needed.
  postgresql/helpers.go
  postgresql/provider.go
  postgresql/resource_postgresql_database.go
  postgresql/resource_postgresql_database_test.go
  postgresql/resource_postgresql_default_privileges.go
  postgresql/resource_postgresql_extension_test.go
  postgresql/resource_postgresql_grant.go
  postgresql/resource_postgresql_role.go
  postgresql/resource_postgresql_role_test.go
  postgresql/resource_postgresql_schema.go
  postgresql/resource_postgresql_schema_test.go
  postgresql/utils_test.go
  tests/env.sh
  tests/switch_rds.sh
  tests/switch_superuser.sh
  tests/testacc_cleanup.sh
  tests/testacc_full.sh
  tests/testacc_setup.sh
  tests/wait-postgres-docker.sh
Labels: size/XL

#149 Update postgresql_grant.html.markdown
  website/docs/r/postgresql_grant.html.markdown
Labels: documentation, size/XS

#162 Fix withRolesGranted permissions troubles.
  postgresql/config.go
  postgresql/helpers.go
  postgresql/resource_postgresql_database.go
  postgresql/resource_postgresql_role.go
  postgresql/resource_postgresql_role_test.go
Labels: size/L

#158 Fix resource attribute key for bypass RLS flag
  postgresql/resource_postgresql_role.go
Labels: size/XS
