Repository terraform-providers/terraform-provider-postgresql, pull requests merged in 2020-06, with the labels that each got.

#145 Use fmt.Errorf() instead of errwrap.Wrapf()
  .travis.yml
  go.mod
  postgresql/config.go
  postgresql/helpers.go
  postgresql/provider.go
  postgresql/resource_postgresql_database.go
  postgresql/resource_postgresql_default_privileges.go
  postgresql/resource_postgresql_extension.go
  postgresql/resource_postgresql_grant.go
  postgresql/resource_postgresql_role.go
  postgresql/resource_postgresql_schema.go
  postgresql/resource_postgresql_schema_test.go
  postgresql/utils_test.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/lib/pq/.travis.sh
  vendor/github.com/lib/pq/.travis.yml
  vendor/github.com/lib/pq/README.md
  vendor/github.com/lib/pq/buf.go
  vendor/github.com/lib/pq/conn.go
  vendor/github.com/lib/pq/conn_go18.go
  vendor/github.com/lib/pq/connector.go
  vendor/github.com/lib/pq/copy.go
  vendor/github.com/lib/pq/doc.go
  vendor/github.com/lib/pq/encode.go
  vendor/github.com/lib/pq/error.go
  vendor/github.com/lib/pq/oid/gen.go
  vendor/github.com/lib/pq/scram/scram.go
  vendor/github.com/lib/pq/ssl.go
  vendor/github.com/lib/pq/ssl_go1.7.go
  vendor/github.com/lib/pq/ssl_renegotiation.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#144 add feature grant functions
  CHANGELOG.md
  postgresql/helpers.go
  postgresql/resource_postgresql_default_privileges.go
  postgresql/resource_postgresql_grant.go
  postgresql/resource_postgresql_grant_test.go
  website/docs/r/postgresql_default_privileges.html.markdown
  website/docs/r/postgresql_grant.html.markdown
Labels: documentation, size/M

#151 update docs to reflect support added for database grants
  website/docs/r/postgresql_grant.html.markdown
Labels: documentation, size/XS
